### ISSUE TITLE
MicroProfile not suitable for use with Precompiled Header files.

### ISSUE THREAD

**Issue by jpvanoosten** [dougbinks/microprofile#1]
I'm using Precompiled header files in my project and it doesn't seem like there is any easy way to use MicroProfile together with precompiled header files.

Use Case:

My graphics library uses a precompiled header file to reduce compile times. In the PCH, I include "microprofile.h" and "microprofileui.h". I can't provide the `MICROPROFILE_IMPL` macro in the PCH file because then every compilation unit will include the declarations.

As a work-around, I created a microprofile.cpp file which includes the `MICROPROFILE_IMPL` and `MICROPROFILEUI_IMPL` macros before the "microprofile.h" and "microprofileui.h" headers. Using precompiled headers on this source file needs to be disable so that the compiler does not expect to see the `#include "PrecompiledHeader.h"` at the top of the file (also macros declared before the precompiled header file are ignored when using precompiled header files.

The other problem arises when I needed to make source code changes to microprofiler.h or microprofilerui.h. Any modification of theses files triggered a full recompile of my entire project (several hundred source files).

Suggestion:

Split the declarations and definitions into separate files and remove the requirement for the `MICROPROFILE_IMPL` macros.

I started doing this in my own project but there are so many places where there are platform specific macros (like `MICROPROFILE_GPU_TIMERS_D3D11`, `MICROPROFILE_GPU_TIMERS_D3D12`, and `MICROPROFILE_GPU_TIMERS_GL`) mixed in between. And some functions were not declared in the correct macro scope (like `MicroProfileGpuFlip(void*)` and `MicroProfileGpuShutdown()` were missing. At some point while trying to port portions of the code to a separate implementation file, I got frustrated and gave up.

Splitting declarations and definitions in separate files would be great and allow microprofile to be easily used in projects using precompiled header files.

**Comment by dougbinks** [comment]
Thanks, however this is just a clone of
https://bitbucket.org/jonasmeyer/microprofile please submit issues there.

**Comment by jpvanoosten** [comment]
Doug,

Thanks for the suggestion. Since I don't have a bitbucket account, I decided to clone this repository and implement this change myself. I'll create a pull request when it is finished.

**Comment by dougbinks** [comment]
Note that I can't easily accept pull requests to this report since its a
clone of the bit bucket one and I'm not the maintainer.

**Comment by jpvanoosten** [comment]
I'm not sure how to create a pull request to a bitbucket repository.

I'll do it for my own projects then.

Thanks anyways.

**Comment by dougbinks** [comment]
It's rather difficult, mainly because the repo is Mecurial and not Git.
